### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qizq1337** [StvnedEagle1337/DesireScrape#1]
```
XXX lineno: 344, opcode: 117
XXX lineno: 344, opcode: 48
XXX lineno: 398, opcode: 48
XXX lineno: 410, opcode: 48
Traceback (most recent call last):
  File "<frozen ChatSaver>", line 344, in assert_builtin
SystemError: unknown opcode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen ChatSaver>", line 398, in protect_pytransform
  File "<frozen ChatSaver>", line 344, in assert_builtin
SystemError: unknown opcode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen ChatSaver>", line 410, in <module>
  File "<frozen ChatSaver>", line 398, in protect_pytransform
SystemError: unknown opcode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<C:\Users\qizq\Desktop\DesireScrape-main\ChatSaver.py>", line 3, in <module>
  File "<frozen ChatSaver>", line 410, in <module>
SystemError: unknown opcode
``` 

bruh

**Comment by StvnedEagle1337** [comment]
its ur python version

**Comment by qizq1337** [comment]
proof

**Comment by 1800s** [comment]
skill issue

**Comment by StvnedEagle1337** [comment]
fr

**Comment by qizq1337** [comment]
> skill issue

says u LOL

btw eagle has u ratted



OK BYE

**Comment by StvnedEagle1337** [comment]
The Qizq i miss, Now he just fuycks my discord

**Comment by qizq1337** [comment]
> The Qizq i miss, Now he just fuycks my discord

p-prof
